services:
  teamspeak:
    image: docker.io/teamspeaksystems/teamspeak6-server:latest
    restart: unless-stopped
    environment:
      TSSERVER_LICENSE_ACCEPTED: accept
      TSSERVER_QUERY_SSH_ENABLED: "true"
      TSSERVER_QUERY_ADMIN_PASSWORD: ${TS_QUERY_PASSWORD}
      TSSERVER_QUERY_ALLOW_LIST: /var/tsserver/query_ip_allowlist.txt
    ports:
      - "9987:9987/udp"
      - "10022:10022"
      - "30033:30033"
    volumes:
      - teamspeak-data:/var/tsserver:U
      - ./teamspeak/query_ip_allowlist.txt:/var/tsserver/query_ip_allowlist.txt:Z

  bot:
    image: ghcr.io/miguelmoraesp/ts-discord-monitor:latest
    restart: unless-stopped
    depends_on:
      - teamspeak
    env_file:
      - .env
    volumes:
      - ./data:/app/data

volumes:
  teamspeak-data:
    external: true
